csharp
// <auto-generated/>
using System.Collections.Generic; // Необходим для List<string>

namespace MyDatingProfileHelper.Backend.Api.DTOs
{
    /// <summary>
    /// DTO для представления профиля пользователя на уровне API (HTTP).
    /// Этот объект используется для отправки данных профиля клиенту.
    /// </summary>
    public class UserProfileDto
    {
        /// <summary>
        /// Имя пользователя.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Описание профиля пользователя.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Список ссылок на фотографии пользователя.
        /// </summary>
        public List<string> Photos { get; set; }

        // Добавьте другие свойства профиля, которые должны быть доступны через API
        // Например:
        // public List<string> Interests { get; set; }
        // public List<string> DatingGoals { get; set; }
        // public int CrystalBalance { get; set; } // Если баланс кристаллов виден в профиле через API

        /// <summary>
        /// Пол пользователя.
        /// </summary>
        public string Gender { get; set; }
    }
}