csharp
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyDatingProfileHelper.Backend.Domain.Models
{
    /// <summary>
    /// Представляет информацию профиля знакомств пользователя, хранящуюся в базе данных.
    /// </summary>
    public class UserProfile // Модель данных профиля пользователя
    {
        /// <summary>
        /// Gets or sets the unique identifier for the user profile.
        /// This is the primary key.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Получает или устанавливает идентификатор пользователя, которому принадлежит этот профиль.
        /// This is a foreign key to the User table.
        /// </summary>
        [ForeignKey("User")]
        public int UserId { get; set; }

        /// <summary>
        /// Получает или устанавливает имя пользователя.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Получает или устанавливает фотографии пользователя.
        /// Stored as a string, can be a JSON string of URLs later.
        /// </summary>
        public string Photos { get; set; }

        /// <summary>
        /// Получает или устанавливает интересы пользователя.
        /// Stored as a string, can be a JSON string of interests later.
        /// </summary>
        public string Interests { get; set; }

        /// <summary>
        /// Получает или устанавливает цели знакомства пользователя.
        /// Stored as a string, can be a JSON string of goals later.
        /// </summary>
        public string DatingGoals { get; set; }

        /// <summary>
        /// Получает или устанавливает текстовое описание профиля пользователя.
        /// </summary>
        public string Description { get; set; }
        
        /// <summary>
        /// Получает или устанавливает интересы пользователя (что нравится).
        /// Может храниться как JSON строка или список строк.
        /// </summary>
        public string Likes { get; set; } // Новое поле: Что нравится

        /// <summary>
        /// Получает или устанавливает то, что не нравится пользователю.
        /// Может храниться как JSON строка или список строк.
        /// </summary>
        public string Dislikes { get; set; } // Новое поле: Что не нравится

        /// <summary>
        /// Получает или устанавливает отношение пользователя к вредным привычкам (например, курение, алкоголь).
        /// Может храниться как строка или представлять ENUM.
        /// </summary>
        public string HabitsAttitude { get; set; } // Новое поле: Отношение к вредным привычкам

        /// <summary>
        /// Получает или устанавливает внешние параметры пользователя (рост, цвет волос, телосложение и т.д.).
        /// Может храниться как JSON строка или набор отдельных полей.
        /// Для простоты пока строка.
        /// </summary>
        public string Appearance { get; set; } // Новое поле: Внешние параметры

        /// <summary>
        /// Получает или устанавливает пол пользователя.
        /// Может храниться как строка ("Мужской", "Женский") или ENUM.
        /// </summary>
        public string Gender { get; set; } // Новое поле: Пол пользователя

        /// <summary>
        /// Gets or sets the navigation property to the User this profile belongs to.
        /// </summary>
        public User User { get; set; }
    }
}